{"abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","text":"ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"AsyncMoya"}],"roleHeading":"Case","title":"DataError.customError(_:)","externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF","symbolKind":"case"},"references":{"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"type":"topic","title":"DataError","kind":"symbol","url":"\/documentation\/asyncmoya\/dataerror","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}]},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"type":"topic","title":"ResponseError","role":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","url":"\/documentation\/asyncmoya\/responseerror","navigatorTitle":[{"text":"ResponseError","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseError","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다.","type":"text"}]},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError"},{"kind":"text","text":")"}],"url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)","kind":"symbol","title":"DataError.customError(_:)","role":"symbol","type":"topic","abstract":[{"text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다.","type":"text"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)"},"doc://AsyncMoya/documentation/AsyncMoya":{"type":"topic","title":"AsyncMoya","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","url":"\/documentation\/asyncmoya","abstract":[{"text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리","type":"text"}],"role":"collection","kind":"symbol"}}}