{"metadata":{"title":"DataError.customError(_:)","modules":[{"name":"AsyncMoya"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ResponseError","kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"text":")","kind":"text"}],"roleHeading":"Case","role":"symbol","externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"kind":"symbol","abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ResponseError","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"kind":"symbol","title":"AsyncMoya","type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","url":"\/documentation\/asyncmoya","abstract":[{"text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리","type":"text"}],"role":"collection"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"title":"DataError","url":"\/documentation\/asyncmoya\/dataerror","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataError"}],"abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataError"}],"type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"role":"symbol","url":"\/documentation\/asyncmoya\/responseerror","title":"ResponseError","abstract":[{"text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다.","type":"text"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"ResponseError","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)","abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"DataError.customError(_:)","role":"symbol"}}}