{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ResponseError","kind":"typeIdentifier","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"text":")","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"sections":[],"identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"metadata":{"roleHeading":"Case","externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF","modules":[{"name":"AsyncMoya"}],"role":"symbol","title":"DataError.customError(_:)","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","abstract":[{"text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다.","type":"text"}],"url":"\/documentation\/asyncmoya\/responseerror","kind":"symbol","type":"topic","title":"ResponseError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"ResponseError","kind":"identifier"}]},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"role":"symbol","abstract":[{"text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"kind":"text","text":")"}],"title":"DataError.customError(_:)","type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)","kind":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya":{"kind":"symbol","abstract":[{"text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","title":"AsyncMoya","url":"\/documentation\/asyncmoya"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"navigatorTitle":[{"kind":"identifier","text":"DataError"}],"title":"DataError","abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataError"}],"type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","kind":"symbol","url":"\/documentation\/asyncmoya\/dataerror"}}}