{"metadata":{"role":"symbol","modules":[{"name":"AsyncMoya"}],"symbolKind":"case","title":"DataError.customError(_:)","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"url":"\/documentation\/asyncmoya","role":"collection","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"title":"AsyncMoya","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataError"}],"navigatorTitle":[{"kind":"identifier","text":"DataError"}],"type":"topic","title":"DataError","url":"\/documentation\/asyncmoya\/dataerror","role":"symbol","abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"type":"topic","title":"DataError.customError(_:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ResponseError","kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)"},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"ResponseError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/asyncmoya\/responseerror","title":"ResponseError","role":"symbol","type":"topic","abstract":[{"type":"text","text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다."}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError"}}}