{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodingError"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/decodingerror(_:)"]}],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"metadata":{"symbolKind":"case","externalID":"s:9AsyncMoya9DataErrorO08decodingD0yACs0D0_pcACmF","modules":[{"name":"AsyncMoya"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodingError"},{"kind":"text","text":"(any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"title":"DataError.decodingError(_:)","roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"JSON 디코딩 중 발생한 오류를 래핑합니다.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/decodingError(_:)"},"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","title":"AsyncMoya","role":"collection","url":"\/documentation\/asyncmoya","type":"topic","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"kind":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"kind":"symbol","role":"symbol","title":"DataError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataError"}],"url":"\/documentation\/asyncmoya\/dataerror","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataError"}]},"doc://AsyncMoya/documentation/AsyncMoya/DataError/decodingError(_:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodingError","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/asyncmoya\/dataerror\/decodingerror(_:)","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/decodingError(_:)","type":"topic","abstract":[{"text":"JSON 디코딩 중 발생한 오류를 래핑합니다.","type":"text"}],"title":"DataError.decodingError(_:)"}}}