{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError"},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/unknownerror"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"AsyncMoya"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"role":"symbol","externalID":"s:9AsyncMoya9DataErrorO07unknownD0yA2CmF","roleHeading":"Case","title":"DataError.unknownError"},"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"url":"\/documentation\/asyncmoya","role":"collection","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"title":"AsyncMoya","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/unknownError":{"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","kind":"symbol","title":"DataError.unknownError","type":"topic","url":"\/documentation\/asyncmoya\/dataerror\/unknownerror"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataError"}],"navigatorTitle":[{"kind":"identifier","text":"DataError"}],"type":"topic","title":"DataError","url":"\/documentation\/asyncmoya\/dataerror","role":"symbol","abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"}}}