{"abstract":[{"text":"서버에서 정의한 에러 코드","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError\/code","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"AsyncMoya"}],"externalID":"s:9AsyncMoya13ResponseErrorV4codeSSvp","role":"symbol","title":"code"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"paths":["\/documentation\/asyncmoya\/responseerror\/code"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError"]]},"sections":[],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"title":"AsyncMoya","kind":"symbol","url":"\/documentation\/asyncmoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"type":"topic","role":"collection","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya"},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError/code":{"abstract":[{"type":"text","text":"서버에서 정의한 에러 코드"}],"url":"\/documentation\/asyncmoya\/responseerror\/code","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError\/code","title":"code","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"abstract":[{"text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다.","type":"text"}],"role":"symbol","title":"ResponseError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"ResponseError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/asyncmoya\/responseerror","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","type":"topic"}}}