{"kind":"symbol","identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"sections":[],"abstract":[{"text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"]}],"metadata":{"symbolKind":"case","externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF","roleHeading":"Case","title":"DataError.customError(_:)","modules":[{"name":"AsyncMoya"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ResponseError","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV"},{"kind":"text","text":")"}]}]}],"references":{"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","role":"symbol","kind":"symbol","type":"topic","title":"DataError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"url":"\/documentation\/asyncmoya\/dataerror"},"doc://AsyncMoya/documentation/AsyncMoya":{"role":"collection","url":"\/documentation\/asyncmoya","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","kind":"symbol","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"title":"AsyncMoya","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"title":"DataError.customError(_:)","type":"topic","abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","kind":"typeIdentifier","text":"ResponseError"},{"kind":"text","text":")"}],"url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)"},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"abstract":[{"type":"text","text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다."}],"title":"ResponseError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseError"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResponseError"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","url":"\/documentation\/asyncmoya\/responseerror"}}}