{"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"metadata":{"title":"DataError.errorData(_:)","externalID":"s:9AsyncMoya9DataErrorO05errorC0yACSScACmF","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"AsyncMoya"}],"symbolKind":"case","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"서버로부터 받은 오류 메시지 문자열을 직접 저장할 때 사용합니다."}],"variants":[{"paths":["\/documentation\/asyncmoya\/dataerror\/errordata(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/errorData(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"title":"AsyncMoya","abstract":[{"text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리","type":"text"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","url":"\/documentation\/asyncmoya"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"title":"DataError","role":"symbol","abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"url":"\/documentation\/asyncmoya\/dataerror","type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","kind":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/errorData(_:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"DataError.errorData(_:)","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/errorData(_:)","url":"\/documentation\/asyncmoya\/dataerror\/errordata(_:)","type":"topic","abstract":[{"type":"text","text":"서버로부터 받은 오류 메시지 문자열을 직접 저장할 때 사용합니다."}]}}}