{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"AsyncMoya"}],"roleHeading":"Case","role":"symbol","title":"DataError.unknownError","externalID":"s:9AsyncMoya9DataErrorO07unknownD0yA2CmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/unknownerror"]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError"},"references":{"doc://AsyncMoya/documentation/AsyncMoya/DataError/unknownError":{"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"title":"DataError.unknownError","role":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"url":"\/documentation\/asyncmoya\/dataerror\/unknownerror"},"doc://AsyncMoya/documentation/AsyncMoya":{"role":"collection","url":"\/documentation\/asyncmoya","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","kind":"symbol","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"title":"AsyncMoya","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","role":"symbol","kind":"symbol","type":"topic","title":"DataError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"url":"\/documentation\/asyncmoya\/dataerror"}}}